Fix the line with cageui_svg_urls to use tab instead of spaces (#984)
#### Rationale
cageui_svg_urls line in lookup_sets (added as part of related PR) uses
spaces instead of tab causing TC failure:


https://teamcity.labkey.org/buildConfiguration/LabKey_263Release_External_Wnprc_WnprcEhrPostgres2/4068462?expandedTest=build%3A%28id%3A4068462%29%2Cid%3A2000000006

org.openqa.selenium.NoSuchElementException: Expected condition failed:
waiting for xpath=//div[contains(text(), 'Delete Complete')]

#### Related Pull Requests
* https://github.com/LabKey/wnprc-modules/pull/968

#### Changes
* Use tab