26.3 fb ios app production merge fix (#1009)
Updated 4 files to fix the errors being thrown by TeamCity build. My
anesthesiaRecovery dataset will be created manually after deployment, so
these files needed to be updated (per Marty) to ensure the automated
tests know what the dataset will look like.

- datasets_manifest.xml: Added my dataset to the list (fixes TeamCity
error: WNPRC_EHRTest)
- datasets_metadata.xml: Listed all the columns in my dataset (fixes
TeamCity error: WNPRC_EHRTest)
- wnprcEhrTestStudyPolicy.xml: Added my table permissions (fixes
TeamCity error: testMprDataEntry)
- wnprc_ios_appModule.java: Updated my schema after changing my upgrade
script to 0.000-26.000 (fixes TeamCity error: SchemaXMLTestCase)



## Rationale
<!-- Rationale describing why this pull request is needed, what behavior
it's adding/changing/removing, etc. (replace this comment) -->

## Related Pull Requests
- <!-- list of links to related pull requests (replace this comment) -->

## Changes
- <!-- list of descriptions of changes that are worth noting (replace
this comment) -->

<!-- list of standard tasks (remove this comment to enable)
## Tasks 📍
- [ ] Claude Code Review
- [ ] Manual Testing
- [ ] Test Automation
- [ ] Verify Fix
-->